[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "W", "I"]
ignore = []
fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"